version: '3'

services:
  # MySQL Database Service
  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # PHP App Service
  crm-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-app-container
    ports:
      - "80:80"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      DB_HOST: mysql-container
      DB_PORT: 3306
      DB_DATABASE: crm_db
      DB_USERNAME: root
      DB_PASSWORD: root

volumes:
  mysql-data:




#version: '3'
#services:
#  crm-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: crm-app:1.0
#    ports:
#      - "8080:80"
    
